# GAME TIME
GAME_SPEED = 10
CLOCK_TICK_GAME_SPEED = 30
CLOCK_TICK_REFERENCE = 30

# SCREEN
SCREEN_WIDTH = 680
SCREEN_HEIGHT = 420
FONT_SIZE = 32
CAPTION = "Reflexy"

# PLAYER
PLAYER_SPEED = 10
PLAYER_WIDTH = 87
PLAYER_HEIGHT = 70
PLAYER_ACCELERATION = 0.5  # in seconds
PLAYER_ACCELERATION_FUNC = "exp"
PLAYER_DECELERATION = 0.2  # in seconds
PLAYER_DECELERATION_FUNC = "lin"

# SPIDER
SPIDER_VISION = 200
SPIDER_SPEED = 2.5
SPIDER_WIDTH = 70
SPIDER_HEIGHT = 40
SPIDER_EYE_X = 34
SPIDER_EYE_Y = 11
SPAWN_SPIDER = 4
SPIDER_ACCELERATION = 1.5  # in seconds
SPIDER_ACCELERATION_FUNC = "exp"
SPIDER_DECELERATION = 0.2  # in seconds
SPIDER_DECELERATION_FUNC = "lin"

# RAY
RAY_WIDTH = 1068
RAY_HEIGHT = 37
RAY_ORIGIN_X = 21
RAY_ORIGIN_Y = 18
RAY_ANIMATION_TIME = 1

# COOLDOWN
COOLDOWN_SPIDER_FIRE = 3.5
COOLDOWN_PLAYER_IMMUNE = 1.5
TIME_PLAYER_BLINK = 0.1
COOLDOWN_PLAYER_SWORD = 0.5
