# GAME TIME
GAME_SPEED = 10
CLOCK_TICK_GAME_SPEED = 60
CLOCK_TICK_REFERENCE = 30

# SCREEN
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
CAPTION = "Reflexy"

# FONTS
TITLE_FONT = "alagard"
TITLE_FONT_SIZE = 64
SCORE_FONT = "Early GameBoy"
SCORE_FONT_SIZE = 16
TEXT_FONT = "rainyhearts"
TEXT_FONT_SIZE = 36

# ELEMENTS
BUTTOM_INCRESE_WHEN_HOVER = -5

# AI
SCREEN_WIDTH_AI = 300

# ANN
LAYERS = [150, 100, 50]

# PLAYER ANN
PLAYER_VISION_RANGE = 300
PLAYER_VISION_CHANNELS = 61
PLAYER_OUTPUTS = 5

# SPIDER AI
SPIDER_VISION_RANGE = 250
SPIDER_VISION_CHANNELS = 145
SPIDER_OUTPUTS = 6

# PLAYER
START_HP = 1
PLAYER_SPEED = 10
PLAYER_WIDTH = 87
PLAYER_HEIGHT = 70
PLAYER_ACCELERATION = 0.5  # in seconds
PLAYER_ACCELERATION_FUNC = "exp"
PLAYER_DECELERATION = 0.2  # in seconds
PLAYER_DECELERATION_FUNC = "lin"

# SPIDER
SPIDER_SPEED = 2.5
SPIDER_WIDTH = 70
SPIDER_HEIGHT = 40
SPIDER_EYE_X = 34
SPIDER_EYE_Y = 11
TIME_SPAWN_SPIDER = 3
MAX_SPAWN_SPIDER = 5
SPIDER_ACCELERATION = 1.5  # in seconds
SPIDER_ACCELERATION_FUNC = "exp"
SPIDER_DECELERATION = 0.2  # in seconds
SPIDER_DECELERATION_FUNC = "lin"

# RAY
RAY_WIDTH = 1068
RAY_HEIGHT = 37
RAY_ORIGIN_X = 21
RAY_ORIGIN_Y = 18
RAY_ANIMATION_TIME = 2

# COOLDOWN
COOLDOWN_SPIDER_FIRE = 3.5
COOLDOWN_PLAYER_IMMUNE = 1.5
TIME_PLAYER_BLINK = 0.1
COOLDOWN_PLAYER_SWORD = 1.5
